name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # Todos os dias 
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: Platane/snk@v3
        with:
          github_user_name: igorpardinho
          outputs: |
            ./output/pacman-contribution-graph.svg

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: output
