name: Waka Readme


on:
  workflow_dispatch: # permite rodar manualmente
  schedule:
    # roda todo dia à meia-noite UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # Clona seu repositório
      - uses: actions/checkout@v3

      # Executa o WakaTime Readme Action
      - uses: athul/waka-readme@master
        with:
          # Chave da sua conta WakaTime
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          # Mostra o título
          SHOW_TITLE: true

          # Pega atividade dos últimos 7 dias
          TIME_RANGE: last_7_days

          # Pega todas as linguagens
          CODE_LANG: ""

          # Mostra tempo e tempo mascarado
          SHOW_TIME: true
          SHOW_MASKED_TIME: true

          # Linguagens ignoradas
          IGNORED_LANGUAGES: YAML JSON TOML XML CSS HTML HCL

          # Quantidade de linguagens mostradas
          LANG_COUNT: 7

          # Mensagem do commit
          COMMIT_MESSAGE: "chore: update WakaTime stats"

          # Branch onde o README será atualizado
          TARGET_BRANCH: main

          # Caminho do README
          TARGET_PATH: README.md
